pool:
  vmImage: 'Ubuntu-16.04'

strategy:
  maxParallel: 10
  matrix:
    node-10:
      node_version: ^10.10.0
    node-8:
      node_version: ^8.12.0

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'Install dependencies'

- script: |
    yarn build
  displayName: 'Run build script'

- script: |
    yarn test
  displayName: 'Run tests'
